# Generated by Django 6.0 on 2026-09-10 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_animal_owner_alter_animal_breed'),
        ('appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='animal.animal'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='veterinarian',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'VETERINARIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
