# Generated by Django 5.2.3 on 2026-09-28 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owners(apps, schema_editor):
    Animal = apps.get_model("animal", "Animal")
    Appointment = apps.get_model("appointment", "Appointment")
    owners_by_animal = {}
    ambiguous_animals = set()
    appointments = Appointment.objects.filter(
        animal__owner__isnull=True
    ).values_list("animal_id", "pet_owner_id")
    for animal_id, owner_id in appointments.iterator():
        previous_owner = owners_by_animal.setdefault(animal_id, owner_id)
        if previous_owner != owner_id:
            ambiguous_animals.add(animal_id)
    for animal_id, owner_id in owners_by_animal.items():
        if animal_id not in ambiguous_animals:
            Animal.objects.filter(pk=animal_id, owner__isnull=True).update(
                owner_id=owner_id
            )


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
        ('appointment', '0002_remove_appointment_appointment_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_owners, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
