# Generated by Django 6.0 on 2026-09-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_animal_owner_alter_animal_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
