# Generated by Django 6.0 on 2026-09-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_animal_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='symptoms',
        ),
    ]
